"""Database creation

Revision ID: c8d8f50b1c74
Revises: 
Create Date: 2023-09-05 11:39:45.081816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d8f50b1c74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('answer1', sa.String(), nullable=False),
    sa.Column('answer2', sa.String(), nullable=False),
    sa.Column('answer3', sa.String(), nullable=False),
    sa.Column('answer4', sa.String(), nullable=False),
    sa.Column('answer5', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_question', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_table('research')
    op.drop_table('question')
    op.drop_table('role')
    # ### end Alembic commands ###
